# Generated by Django 5.2.8 on 2026-06-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_author_post_cover_post_excerpt_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sidebar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="模块名称")),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("search", "搜索框"),
                            ("new_posts", "最新文章"),
                            ("hot_posts", "热门文章"),
                            ("archives", "按月归档"),
                            ("custom", "自定义内容"),
                        ],
                        default="new_posts",
                        max_length=20,
                        verbose_name="展示类型",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="仅「自定义内容」模块需要填写，支持HTML代码",
                        verbose_name="自定义HTML内容",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="数值越小越靠前，控制侧边栏模块的展示顺序",
                        verbose_name="排序权重",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="是否显示")),
            ],
            options={
                "verbose_name": "侧边栏模块",
                "verbose_name_plural": "侧边栏模块",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="is_hot",
            field=models.BooleanField(
                default=False,
                help_text="站长手动标记，标记后优先展示在侧边栏热门文章模块",
                verbose_name="热门推荐",
            ),
        ),
    ]
