# Generated by Django 6.0.4 on 2026-04-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='post_covers/', verbose_name='文章封面'),
        ),
    ]
