# Generated by Django 5.2.8 on 2026-06-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_sidebar_post_is_hot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sidebar",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_hot",
        ),
        migrations.AddField(
            model_name="post",
            name="is_recommended",
            field=models.BooleanField(
                default=False,
                help_text="勾选后该文章将出现在侧边栏推荐区",
                verbose_name="推荐",
            ),
        ),
    ]
