# Generated by Django 6.0.4 on 2026-04-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, help_text='可选。如果不填写，将自动摘取正文的前 150 个字符。', max_length=200, verbose_name='文章摘要'),
        ),
    ]
