# Generated by Django 6.0.5 on 2026-06-04 03:41

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_sidebar_remove_post_is_hot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(default='探索深度学习的边界，用代码构建智能的未来。', max_length=200, verbose_name='首页标语')),
                ('hero_sub', models.CharField(blank=True, default='深度学习工程师 & AI 技术探索者 · 持续学习中', max_length=200, verbose_name='副标题')),
                ('about_me', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='个人介绍，显示在"关于"卡片中', verbose_name='关于我')),
                ('current_work', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='当前正在进行的工作/项目，显示在"当下"卡片中', verbose_name='当前工作')),
                ('skills_text', models.TextField(blank=True, default='Python、Django、PyTorch、TensorFlow、NumPy、Pandas、Scikit-learn、Git、HTML/CSS、SQL', help_text='多个技能以中文顿号（、）分隔', verbose_name='技能标签')),
                ('hobbies', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='兴趣爱好与长期坚持，显示在"热爱 & 坚持"卡片中', verbose_name='热爱与坚持')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '首页内容',
                'verbose_name_plural': '首页内容',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='正文（富文本）'),
        ),
    ]
