# Generated by Django 6.0.4 on 2026-04-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='可选，支持多行输入。如果不填，则前端不显示摘要。', verbose_name='文章摘要'),
        ),
    ]
