# Generated by Django 6.0.4 on 2026-04-26 14:55

from django.db import migrations, models
from django.utils.text import slugify


def gen_slugs(apps, schema_editor):
    """为已有文章生成唯一的 slug"""
    Post = apps.get_model('blog', 'Post')
    for post in Post.objects.filter(slug=''):
        base_slug = slugify(post.title, allow_unicode=True) or f'post-{post.pk}'
        slug = base_slug
        n = 1
        while Post.objects.filter(slug=slug).exclude(pk=post.pk).exists():
            slug = f'{base_slug}-{n}'
            n += 1
        post.slug = slug
        post.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_excerpt'),
    ]

    operations = [
        # 第一步：先加 slug 列（允许为空，无唯一约束）
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, default='', verbose_name='URL 别名'),
            preserve_default=False,
        ),
        # 第二步：为已有数据生成 slug
        migrations.RunPython(gen_slugs, migrations.RunPython.noop),
        # 第三步：加上唯一约束
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, help_text='可不填，保存时自动根据标题生成。也可以手动输入英文字母、数字和连字符。', verbose_name='URL 别名'),
        ),
    ]
