# Generated by Django 6.0.6 on 2026-06-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_homepage_alter_post_content_alter_sitepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('zh-hans', '中文'), ('en', 'English'), ('ja', '日本語')], default='zh-hans', help_text='文章内容使用的语言', max_length=10, verbose_name='语言'),
        ),
    ]
